In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import tensorflow as tf

In [3]:
!ls

wineQuality.ipynb  wineQuality.py	winequality-white.csv
winequality.names  winequality-red.csv


In [5]:
!cat winequality.names

In [152]:
whiteWine = pd.read_csv('winequality-white.csv',delimiter=';')
#whiteWine['wine']=1
redWine = pd.read_csv('winequality-red.csv',delimiter=';')
#redWine['wine']=0

In [50]:
from sklearn.utils import shuffle
wines = pd.concat([whiteWine,redWine], axis=0, sort=False)
wines = shuffle(wines)
wines.reset_index(inplace=True, drop=True)

In [51]:
wines.shape

(6497, 12)

In [52]:
whiteWine.shape, redWine.shape

((4898, 12), (1599, 12))

In [53]:
wines.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.5             0.650         0.18             7.0      0.088   
1            6.9             0.250         0.24             3.6      0.057   
2            8.3             0.625         0.20             1.5      0.080   
3            5.7             0.460         0.46             1.4      0.040   
4            8.6             0.360         0.26            11.1      0.030   
5            7.0             0.420         0.35             1.6      0.088   
6            6.9             0.320         0.26             2.3      0.030   
7            9.1             0.470         0.49             2.6      0.094   
8           11.4             0.260         0.44             3.6      0.071   
9            8.7             0.700         0.24             2.5      0.226   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 27.0                  94.0  0.99915  3.38       0.77   
1                 13.0                  85.0  0.99420  2.99       0.48   
2                 27.0                 119.0  0.99720  3.16       1.12   
3                 31.0                 169.0  0.99320  3.13       0.47   
4                 43.5                 171.0  0.99480  3.03       0.49   
5                 16.0                  39.0  0.99610  3.34       0.55   
6                 11.0                 103.0  0.99106  3.06       0.42   
7                 38.0                 106.0  0.99820  3.08       0.59   
8                  6.0                  19.0  0.99860  3.12       0.82   
9                  5.0                  15.0  0.99910  3.32       0.60   

   alcohol  quality  
0      9.4        5  
1      9.5        4  
2      9.1        4  
3      8.8        5  
4     12.0        5  
5      9.2        5  
6     11.1        6  
7      9.1        5  
8      9.3        6  
9      9.0        6

In [54]:
quality = wines['quality']

In [55]:
wines.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.5             0.650         0.18             7.0      0.088   
1            6.9             0.250         0.24             3.6      0.057   
2            8.3             0.625         0.20             1.5      0.080   
3            5.7             0.460         0.46             1.4      0.040   
4            8.6             0.360         0.26            11.1      0.030   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 27.0                  94.0  0.99915  3.38       0.77   
1                 13.0                  85.0  0.99420  2.99       0.48   
2                 27.0                 119.0  0.99720  3.16       1.12   
3                 31.0                 169.0  0.99320  3.13       0.47   
4                 43.5                 171.0  0.99480  3.03       0.49   

   alcohol  quality  
0      9.4        5  
1      9.5        4  
2      9.1        4  
3      8.8        5  
4     12.0        5

## Data Preprocess and analysis

In [56]:
wines.tail(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
6487            7.4              0.27         0.49             1.1      0.037   
6488            6.2              0.37         0.24             6.1      0.032   
6489            6.8              0.32         0.23             3.3      0.026   
6490            5.0              0.24         0.19             5.0      0.043   
6491            5.9              0.54         0.00             0.8      0.032   
6492            6.7              0.26         0.26             4.0      0.079   
6493            6.5              0.27         0.19             6.6      0.045   
6494            7.7              0.28         0.24             2.4      0.044   
6495            5.7              0.15         0.28             3.7      0.045   
6496            7.6              0.22         0.34             9.7      0.035   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
6487                 33.0                 156.0  0.99200  3.15       0.54   
6488                 19.0                  86.0  0.98934  3.04       0.26   
6489                 31.0                  99.0  0.98960  3.10       0.40   
6490                 17.0                 101.0  0.99438  3.67       0.57   
6491                 12.0                  82.0  0.99286  3.25       0.36   
6492                 35.5                 216.0  0.99560  3.31       0.68   
6493                 98.0                 175.0  0.99364  3.16       0.34   
6494                 29.0                 157.0  0.99312  3.27       0.56   
6495                 57.0                 151.0  0.99130  3.22       0.27   
6496                 26.0                 143.0  0.99650  3.08       0.49   

      alcohol  quality  
6487     11.1        6  
6488     13.4        8  
6489     12.4        6  
6490     10.0        5  
6491      8.8        5  
6492      9.5        5  
6493     10.1        6  
6494     10.6        6  
6495     11.2        6  
6496      9.8        6

In [57]:
wines.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [58]:
columns = list(wines.columns)
op = 'quality'

In [153]:
corr_dict = {}
for i in range(0,len(columns)):
    if op != columns[i]:
        corr_dict['{}'.format(columns[i])] = whiteWine[columns[i]].corr(whiteWine[op])
        
corr_dict = dict(sorted(corr_dict.items(), key=lambda item: abs(item[1]), reverse=True))

In [154]:
corr_dict

{'alcohol': 0.4355747154613735,
 'density': -0.30712331273472987,
 'chlorides': -0.20993441094676066,
 'volatile acidity': -0.19472296892113433,
 'total sulfur dioxide': -0.17473721759706282,
 'fixed acidity': -0.11366283071301793,
 'pH': 0.09942724573666419,
 'residual sugar': -0.09757682889469317,
 'sulphates': 0.05367787713279209,
 'citric acid': -0.009209090883975429,
 'free sulfur dioxide': 0.008158067123436068}

In [155]:
thresh = 0.05
features = []
for i in columns:
    if i!=op and abs(corr_dict[i])>=thresh:
        features.append(i)
        
print(features)

['fixed acidity', 'volatile acidity', 'residual sugar', 'chlorides', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']


Findings from this:
No significant correlation between any values with quality. A bit with amount of alcohol

In [156]:
wine_features = whiteWine[features]
wine_quality = whiteWine[op]


In [192]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(wine_features, wine_quality, test_size=0.33, random_state=42)

scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [193]:
from sklearn.linear_model import LinearRegression

base = LinearRegression()
base.fit(X_train, y_train)

LinearRegression()

In [194]:
train_pred = base.predict(X_train)
print(train_pred)
test_pred = base.predict(X_test) 
print(test_pred)

[6.4459684  5.63494681 6.52294918 ... 6.17498877 6.2051246  5.83936611]
[6.33274077 6.38031476 6.41642005 ... 5.8959915  6.0091014  5.79396424]


In [195]:
from sklearn import metrics

# calculating rmse
train_rmse = mean_squared_error(train_pred, y_train) ** 0.5
print(train_rmse)
test_rmse = mean_squared_error(test_pred, y_test) ** 0.5
print(test_rmse)# rounding off the predicted values for test set
predicted_data = np.round_(test_pred)
print(predicted_data)
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, test_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, test_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, test_pred)))# displaying coefficients of each feature
coeffecients = pd.DataFrame(base.coef_,features) 
coeffecients.columns = ['Coeffecient'] 
print(coeffecients)

0.7553222838680139
0.7463493602535066
[6. 6. 6. ... 6. 6. 6.]
Mean Absolute Error: 0.5827222658263003
Mean Squared Error: 0.5570373675508186
Root Mean Squared Error: 0.7463493602535066
                      Coeffecient
fixed acidity            0.041819
volatile acidity        -0.205179
residual sugar           0.433248
chlorides                0.005959
total sulfur dioxide     0.039440
density                 -0.458640
pH                       0.104229
sulphates                0.082753
alcohol                  0.254510


In [225]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=len(features),kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(64, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(32, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))

In [226]:
model.compile(loss='mse', optimizer=RMSprop(0.0001), metrics=['mae'])
model.fit(X_train, y_train, validation_split=0.3, epochs=150)

Epoch 1/150
72/72 [==============================] - 0s 4ms/step - loss: 26.0594 - mae: 4.9587 - val_loss: 19.8109 - val_mae: 4.2601
Epoch 2/150
72/72 [==============================] - 0s 4ms/step - loss: 14.1361 - mae: 3.4646 - val_loss: 9.3373 - val_mae: 2.7366
Epoch 3/150
72/72 [==============================] - 0s 4ms/step - loss: 7.0671 - mae: 2.2249 - val_loss: 5.2948 - val_mae: 1.8786
Epoch 4/150
72/72 [==============================] - 0s 3ms/step - loss: 5.0371 - mae: 1.7455 - val_loss: 4.2470 - val_mae: 1.6193
Epoch 5/150
72/72 [==============================] - 0s 3ms/step - loss: 4.2228 - mae: 1.5583 - val_loss: 3.6418 - val_mae: 1.4935
Epoch 6/150
72/72 [==============================] - 0s 3ms/step - loss: 3.6640 - mae: 1.4415 - val_loss: 3.2337 - val_mae: 1.3993
Epoch 7/150
72/72 [==============================] - 0s 3ms/step - loss: 3.2817 - mae: 1.3584 - val_loss: 2.9510 - val_mae: 1.3385
Epoch 8/150
72/72 [==============================] - 0s 2ms/step - loss: 2.9983 

72/72 [==============================] - 0s 2ms/step - loss: 0.5420 - mae: 0.5783 - val_loss: 0.7255 - val_mae: 0.6563
Epoch 64/150
72/72 [==============================] - 0s 2ms/step - loss: 0.5359 - mae: 0.5746 - val_loss: 0.7221 - val_mae: 0.6559
Epoch 65/150
72/72 [==============================] - 0s 2ms/step - loss: 0.5325 - mae: 0.5725 - val_loss: 0.7115 - val_mae: 0.6494
Epoch 66/150
72/72 [==============================] - 0s 2ms/step - loss: 0.5230 - mae: 0.5685 - val_loss: 0.7107 - val_mae: 0.6482
Epoch 67/150
72/72 [==============================] - 0s 2ms/step - loss: 0.5185 - mae: 0.5650 - val_loss: 0.7034 - val_mae: 0.6466
Epoch 68/150
72/72 [==============================] - 0s 2ms/step - loss: 0.5115 - mae: 0.5594 - val_loss: 0.7181 - val_mae: 0.6526
Epoch 69/150
72/72 [==============================] - 0s 3ms/step - loss: 0.5113 - mae: 0.5607 - val_loss: 0.6946 - val_mae: 0.6428
Epoch 70/150
72/72 [==============================] - 0s 2ms/step - loss: 0.5031 - mae: 0

Epoch 125/150
72/72 [==============================] - 0s 2ms/step - loss: 0.3800 - mae: 0.4803 - val_loss: 0.6107 - val_mae: 0.5997
Epoch 126/150
72/72 [==============================] - 0s 2ms/step - loss: 0.3785 - mae: 0.4796 - val_loss: 0.6042 - val_mae: 0.5935
Epoch 127/150
72/72 [==============================] - 0s 4ms/step - loss: 0.3773 - mae: 0.4786 - val_loss: 0.6112 - val_mae: 0.6002
Epoch 128/150
72/72 [==============================] - 0s 4ms/step - loss: 0.3772 - mae: 0.4772 - val_loss: 0.6038 - val_mae: 0.5953
Epoch 129/150
72/72 [==============================] - 0s 3ms/step - loss: 0.3744 - mae: 0.4781 - val_loss: 0.6124 - val_mae: 0.6012
Epoch 130/150
72/72 [==============================] - 0s 5ms/step - loss: 0.3724 - mae: 0.4770 - val_loss: 0.6037 - val_mae: 0.5958
Epoch 131/150
72/72 [==============================] - 0s 5ms/step - loss: 0.3713 - mae: 0.4732 - val_loss: 0.6042 - val_mae: 0.5947
Epoch 132/150
72/72 [==============================] - 0s 3ms/step - 

In [227]:
model.evaluate(X_test, y_test)

51/51 [==============================] - 0s 1ms/step - loss: 0.5967 - mae: 0.5941


[0.5966840982437134, 0.5940666198730469]

In [228]:
pred = model.predict(X_test)

In [229]:
scaler.mean_

array([6.86321244e+00, 2.79100884e-01, 6.43267297e+00, 4.55236208e-02,
       1.38148888e+02, 9.94053130e-01, 3.18971960e+00, 4.89457482e-01,
       1.05131616e+01])

In [230]:
#pred = np.around(pred)
y_tes = list(y_test)

In [232]:
accuracy_score(np.around(pred), y_test)

0.5269016697588126